import type {
  Product,
  Category,
  Brand,
  Order,
  User,
  StylistRequest,
  StylistCode,
  Coupon,
} from './types';

// TODO: Replace with API call - GET /api/categories
export const categories: Category[] = [
  { id: '1', name: 'Hair Color', slug: 'hair-color', productCount: 45 },
  { id: '2', name: 'Shampoo', slug: 'shampoo', productCount: 32 },
  { id: '3', name: 'Mask', slug: 'mask', productCount: 28 },
  { id: '4', name: 'Activator', slug: 'activator', productCount: 12 },
  { id: '5', name: 'Spray', slug: 'spray', productCount: 18 },
  { id: '6', name: 'Fluid', slug: 'fluid', productCount: 15 },
  { id: '7', name: 'Lotion', slug: 'lotion', productCount: 22 },
  { id: '8', name: 'Bleach and De Color', slug: 'bleach-decolor', productCount: 8 },
  { id: '9', name: 'Tester', slug: 'tester', productCount: 10 },
  { id: '10', name: 'Filler', slug: 'filler', productCount: 6 },
  { id: '11', name: 'Color Mask', slug: 'color-mask', productCount: 14 },
  { id: '12', name: 'Styling', slug: 'styling', productCount: 25 },
  { id: '13', name: 'Hydrogen Peroxide', slug: 'hydrogen-peroxide', productCount: 9 },
  { id: '14', name: 'Conditioner', slug: 'conditioner', productCount: 30 },
  { id: '15', name: 'Sets', slug: 'sets', productCount: 12 },
  { id: '16', name: 'Other', slug: 'other', productCount: 20 },
];

// TODO: Replace with API call - GET /api/brands
export const brands: Brand[] = [
  { id: '1', name: 'Fanola', slug: 'fanola', productCount: 85 },
  { id: '2', name: 'Oro Therapy', slug: 'oro-therapy', productCount: 42 },
  { id: '3', name: 'Rr Line', slug: 'rr-line', productCount: 56 },
  { id: '4', name: 'No Yellow Color', slug: 'no-yellow-color', productCount: 28 },
  { id: '5', name: 'Other', slug: 'other', productCount: 35 },
];

// TODO: Replace with API call - GET /api/products
export const products: Product[] = [
  {
    id: '1',
    name: 'No Yellow Shampoo',
    slug: 'no-yellow-shampoo',
    brand: 'Fanola',
    category: 'Shampoo',
    description: 'Professional anti-yellow shampoo for gray, super lightened or decolored hair. Its violet pigment neutralizes unwanted yellow tones leaving hair soft and shiny.',
    ingredients: 'Aqua, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Chloride, Parfum, Glycerin...',
    usage: 'Apply to wet hair, massage gently, leave on for 1-5 minutes depending on desired intensity, then rinse thoroughly.',
    images: ['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '1-100', size: '100ml', retailPrice: 12.99, stylistPrice: 9.99, stock: 50 },
      { id: '1-350', size: '350ml', retailPrice: 24.99, stylistPrice: 18.99, stock: 30 },
      { id: '1-1000', size: '1000ml', retailPrice: 49.99, stylistPrice: 37.99, stock: 20 },
    ],
    isNew: false,
    isSale: true,
    salePercent: 15,
    rating: 4.8,
    reviewCount: 342,
    status: 'active',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Oro Puro Illuminating Mask',
    slug: 'oro-puro-illuminating-mask',
    brand: 'Oro Therapy',
    category: 'Mask',
    description: 'Luxurious hair mask enriched with 24K gold microparticles and argan oil. Provides intense nourishment and exceptional shine.',
    ingredients: 'Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Gold, Argania Spinosa Kernel Oil...',
    usage: 'After shampooing, apply to damp hair from mid-length to ends. Leave for 3-5 minutes and rinse.',
    images: ['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '2-300', size: '300ml', retailPrice: 32.99, stylistPrice: 24.99, stock: 25 },
      { id: '2-1000', size: '1000ml', retailPrice: 79.99, stylistPrice: 59.99, stock: 15 },
    ],
    isNew: true,
    isSale: false,
    rating: 4.9,
    reviewCount: 128,
    status: 'active',
    createdAt: '2024-06-01',
  },
  {
    id: '3',
    name: 'Energy Hair Lotion',
    slug: 'energy-hair-lotion',
    brand: 'Rr Line',
    category: 'Lotion',
    description: 'Intensive energizing lotion that helps prevent hair loss and stimulates growth. Contains natural plant extracts.',
    ingredients: 'Alcohol Denat, Aqua, Menthol, Capsicum Frutescens Extract, Caffeine...',
    usage: 'Apply directly to scalp and massage gently. Do not rinse. Use 2-3 times per week.',
    images: ['/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '3-125', size: '125ml', retailPrice: 28.99, stylistPrice: 21.99, stock: 40 },
    ],
    isNew: false,
    isSale: false,
    rating: 4.5,
    reviewCount: 89,
    status: 'active',
    createdAt: '2023-11-20',
  },
  {
    id: '4',
    name: 'No Yellow Color Cream',
    slug: 'no-yellow-color-cream',
    brand: 'No Yellow Color',
    category: 'Hair Color',
    description: 'Professional permanent hair color with anti-yellow technology. Provides long-lasting color with maximum gray coverage.',
    ingredients: 'Aqua, Cetearyl Alcohol, Propylene Glycol, Ethanolamine, Oleic Acid...',
    usage: 'Mix with appropriate developer. Apply evenly, process for 30-45 minutes, then rinse and condition.',
    images: ['/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '4-100', size: '100ml', retailPrice: 15.99, stylistPrice: 11.99, stock: 100 },
    ],
    isNew: false,
    isSale: true,
    salePercent: 10,
    rating: 4.7,
    reviewCount: 256,
    status: 'active',
    createdAt: '2023-08-10',
  },
  {
    id: '5',
    name: 'Keratin Restructuring Spray',
    slug: 'keratin-restructuring-spray',
    brand: 'Fanola',
    category: 'Spray',
    description: 'Leave-in keratin spray that repairs and protects damaged hair. Provides thermal protection and reduces frizz.',
    ingredients: 'Aqua, Hydrolyzed Keratin, Cyclomethicone, Dimethicone, Panthenol...',
    usage: 'Spray on damp or dry hair. Do not rinse. Style as desired.',
    images: ['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '5-200', size: '200ml', retailPrice: 19.99, stylistPrice: 14.99, stock: 35 },
    ],
    isNew: true,
    isSale: false,
    rating: 4.6,
    reviewCount: 167,
    status: 'active',
    createdAt: '2024-05-15',
  },
  {
    id: '6',
    name: 'Hydrogen Peroxide Developer',
    slug: 'hydrogen-peroxide-developer',
    brand: 'Fanola',
    category: 'Hydrogen Peroxide',
    description: 'Professional oxidizing emulsion for use with permanent hair color. Available in multiple volumes for different lifting needs.',
    ingredients: 'Aqua, Hydrogen Peroxide, Cetearyl Alcohol, Ceteareth-20...',
    usage: 'Mix with permanent color according to instructions. Apply immediately after mixing.',
    images: ['/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '6-1000', size: '1000ml', retailPrice: 14.99, stylistPrice: 10.99, stock: 60 },
    ],
    isNew: false,
    isSale: false,
    rating: 4.4,
    reviewCount: 78,
    status: 'active',
    createdAt: '2023-06-01',
  },
  {
    id: '7',
    name: 'Smoothing Styling Fluid',
    slug: 'smoothing-styling-fluid',
    brand: 'Oro Therapy',
    category: 'Fluid',
    description: 'Lightweight styling fluid that tames frizz and adds brilliant shine. Infused with argan oil and gold particles.',
    ingredients: 'Cyclopentasiloxane, Dimethiconol, Argania Spinosa Kernel Oil, Gold...',
    usage: 'Apply a few drops to damp or dry hair, focusing on ends. Style as desired.',
    images: ['/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '7-100', size: '100ml', retailPrice: 22.99, stylistPrice: 16.99, stock: 45 },
    ],
    isNew: false,
    isSale: true,
    salePercent: 20,
    rating: 4.8,
    reviewCount: 203,
    status: 'active',
    createdAt: '2023-09-25',
  },
  {
    id: '8',
    name: 'Ultra Volume Conditioner',
    slug: 'ultra-volume-conditioner',
    brand: 'Rr Line',
    category: 'Conditioner',
    description: 'Lightweight conditioner that provides volume without weighing hair down. Ideal for fine and flat hair.',
    ingredients: 'Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Panthenol, Hydrolyzed Wheat Protein...',
    usage: 'After shampooing, apply to hair lengths and ends. Leave for 2-3 minutes and rinse thoroughly.',
    images: ['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '8-250', size: '250ml', retailPrice: 16.99, stylistPrice: 12.99, stock: 55 },
      { id: '8-1000', size: '1000ml', retailPrice: 39.99, stylistPrice: 29.99, stock: 25 },
    ],
    isNew: false,
    isSale: false,
    rating: 4.3,
    reviewCount: 145,
    status: 'active',
    createdAt: '2023-10-12',
  },
  {
    id: '9',
    name: 'Color Activator',
    slug: 'color-activator',
    brand: 'Fanola',
    category: 'Activator',
    description: 'Professional color activator for use with semi-permanent and demi-permanent colors. Ensures optimal color development.',
    ingredients: 'Aqua, Hydrogen Peroxide, Phosphoric Acid, Sodium Stannate...',
    usage: 'Mix with color according to manufacturer instructions. Apply immediately.',
    images: ['/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '9-1000', size: '1000ml', retailPrice: 18.99, stylistPrice: 13.99, stock: 40 },
    ],
    isNew: false,
    isSale: false,
    rating: 4.5,
    reviewCount: 92,
    status: 'active',
    createdAt: '2023-07-08',
  },
  {
    id: '10',
    name: 'Blue Bleach Powder',
    slug: 'blue-bleach-powder',
    brand: 'Fanola',
    category: 'Bleach and De Color',
    description: 'Professional blue bleaching powder with anti-yellow properties. Provides up to 7 levels of lift.',
    ingredients: 'Potassium Persulfate, Sodium Silicate, Magnesium Carbonate, Sodium Metasilicate...',
    usage: 'Mix with appropriate volume developer. Apply to dry hair, monitor closely, rinse when desired lift is achieved.',
    images: ['/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '10-500', size: '500g', retailPrice: 29.99, stylistPrice: 22.99, stock: 30 },
    ],
    isNew: false,
    isSale: false,
    rating: 4.7,
    reviewCount: 184,
    status: 'active',
    createdAt: '2023-05-20',
  },
  {
    id: '11',
    name: 'Purple Color Mask',
    slug: 'purple-color-mask',
    brand: 'Fanola',
    category: 'Color Mask',
    description: 'Toning color mask that neutralizes yellow and brassy tones. Conditions while depositing vibrant purple pigment.',
    ingredients: 'Aqua, Cetearyl Alcohol, Basic Violet 2, Behentrimonium Chloride...',
    usage: 'Apply to clean, damp hair. Leave for 5-15 minutes depending on desired intensity. Rinse thoroughly.',
    images: ['/placeholder.svg?height=600&width=600', '/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '11-200', size: '200ml', retailPrice: 18.99, stylistPrice: 14.99, stock: 50 },
    ],
    isNew: true,
    isSale: false,
    rating: 4.9,
    reviewCount: 312,
    status: 'active',
    createdAt: '2024-04-01',
  },
  {
    id: '12',
    name: 'Bond Filler Treatment',
    slug: 'bond-filler-treatment',
    brand: 'Oro Therapy',
    category: 'Filler',
    description: 'Advanced bond repair treatment that restores damaged hair structure. Rebuilds broken bonds from chemical treatments.',
    ingredients: 'Aqua, Bis-Aminopropyl Diglycol Dimaleate, Propylene Glycol, Citric Acid...',
    usage: 'Apply to towel-dried hair. Leave for 10 minutes, then rinse. Use weekly for best results.',
    images: ['/placeholder.svg?height=600&width=600'],
    sizes: [
      { id: '12-100', size: '100ml', retailPrice: 45.99, stylistPrice: 34.99, stock: 20 },
      { id: '12-250', size: '250ml', retailPrice: 89.99, stylistPrice: 67.99, stock: 10 },
    ],
    isNew: false,
    isSale: true,
    salePercent: 25,
    rating: 4.8,
    reviewCount: 97,
    status: 'active',
    createdAt: '2024-02-14',
  },
];

// TODO: Replace with API call - GET /api/users
export const users: User[] = [
  { id: '1', email: 'admin@tessa.com', name: 'Admin User', role: 'admin', createdAt: '2023-01-01' },
  { id: '2', email: 'distributor@tessa.com', name: 'Distributor Pro', role: 'distributor', createdAt: '2023-03-15' },
  { id: '3', email: 'stylist@salon.com', name: 'Sarah Styles', role: 'stylist', phone: '+1 555-0123', createdAt: '2023-06-20' },
  { id: '4', email: 'user@email.com', name: 'John Customer', role: 'user', phone: '+1 555-0456', createdAt: '2024-01-10' },
  { id: '5', email: 'guest@temp.com', name: 'Guest User', role: 'guest', createdAt: '2024-06-01' },
];

// TODO: Replace with API call - GET /api/orders
export const orders: Order[] = [
  {
    id: 'ORD-001',
    userId: '4',
    items: [
      { id: '1', productId: '1', productName: 'No Yellow Shampoo', productImage: '/placeholder.svg?height=100&width=100', brand: 'Fanola', size: '350ml', price: 24.99, quantity: 2 },
      { id: '2', productId: '2', productName: 'Oro Puro Illuminating Mask', productImage: '/placeholder.svg?height=100&width=100', brand: 'Oro Therapy', size: '300ml', price: 32.99, quantity: 1 },
    ],
    status: 'delivered',
    subtotal: 82.97,
    discount: 8.30,
    shipping: 5.99,
    total: 80.66,
    shippingAddress: {
      fullName: 'John Customer',
      phone: '+1 555-0456',
      street: '123 Main Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
    paymentMethod: 'cod',
    couponCode: 'WELCOME10',
    createdAt: '2024-05-15T10:30:00Z',
    updatedAt: '2024-05-20T14:00:00Z',
    statusHistory: [
      { status: 'pending', date: '2024-05-15T10:30:00Z' },
      { status: 'confirmed', date: '2024-05-15T11:00:00Z' },
      { status: 'processing', date: '2024-05-16T09:00:00Z' },
      { status: 'shipped', date: '2024-05-17T14:00:00Z' },
      { status: 'delivered', date: '2024-05-20T14:00:00Z' },
    ],
  },
  {
    id: 'ORD-002',
    userId: '3',
    items: [
      { id: '3', productId: '10', productName: 'Blue Bleach Powder', productImage: '/placeholder.svg?height=100&width=100', brand: 'Fanola', size: '500g', price: 22.99, quantity: 3 },
      { id: '4', productId: '6', productName: 'Hydrogen Peroxide Developer', productImage: '/placeholder.svg?height=100&width=100', brand: 'Fanola', size: '1000ml', price: 10.99, quantity: 5 },
    ],
    status: 'shipped',
    subtotal: 123.92,
    discount: 0,
    shipping: 0,
    total: 123.92,
    shippingAddress: {
      fullName: 'Sarah Styles',
      phone: '+1 555-0123',
      street: '456 Salon Avenue',
      city: 'Los Angeles',
      state: 'CA',
      zipCode: '90001',
      country: 'USA',
    },
    paymentMethod: 'cod',
    createdAt: '2024-06-10T09:15:00Z',
    updatedAt: '2024-06-12T16:00:00Z',
    statusHistory: [
      { status: 'pending', date: '2024-06-10T09:15:00Z' },
      { status: 'confirmed', date: '2024-06-10T10:00:00Z' },
      { status: 'processing', date: '2024-06-11T08:00:00Z' },
      { status: 'shipped', date: '2024-06-12T16:00:00Z' },
    ],
  },
  {
    id: 'ORD-003',
    userId: '4',
    items: [
      { id: '5', productId: '5', productName: 'Keratin Restructuring Spray', productImage: '/placeholder.svg?height=100&width=100', brand: 'Fanola', size: '200ml', price: 19.99, quantity: 1 },
    ],
    status: 'pending',
    subtotal: 19.99,
    discount: 0,
    shipping: 5.99,
    total: 25.98,
    shippingAddress: {
      fullName: 'John Customer',
      phone: '+1 555-0456',
      street: '123 Main Street',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      country: 'USA',
    },
    paymentMethod: 'cod',
    createdAt: '2024-06-14T14:20:00Z',
    updatedAt: '2024-06-14T14:20:00Z',
    statusHistory: [
      { status: 'pending', date: '2024-06-14T14:20:00Z' },
    ],
  },
];

// TODO: Replace with API call - GET /api/stylist-requests
export const stylistRequests: StylistRequest[] = [
  {
    id: 'REQ-001',
    userId: '6',
    userName: 'Maria Beauty',
    userEmail: 'maria@beautysalon.com',
    businessName: 'Maria Beauty Salon',
    businessAddress: '789 Beauty Lane, Miami, FL 33101',
    businessPhone: '+1 555-0789',
    licenseNumber: 'FL-COSM-12345',
    status: 'pending',
    createdAt: '2024-06-12T08:00:00Z',
  },
  {
    id: 'REQ-002',
    userId: '7',
    userName: 'Alex Cuts',
    userEmail: 'alex@alexcuts.com',
    businessName: 'Alex Cuts Studio',
    businessAddress: '321 Style Street, Chicago, IL 60601',
    businessPhone: '+1 555-0321',
    stylistCode: 'DIST-ABC123',
    status: 'approved',
    createdAt: '2024-06-01T10:30:00Z',
    reviewedAt: '2024-06-01T10:30:00Z',
  },
  {
    id: 'REQ-003',
    userId: '8',
    userName: 'Test Fake',
    userEmail: 'fake@fake.com',
    businessName: 'Fake Salon',
    businessAddress: '000 Nowhere, XX 00000',
    businessPhone: '+1 555-0000',
    status: 'rejected',
    createdAt: '2024-05-20T15:00:00Z',
    reviewedAt: '2024-05-21T09:00:00Z',
    reviewedBy: 'Admin User',
    rejectionReason: 'Unable to verify business information',
  },
];

// TODO: Replace with API call - GET /api/stylist-codes
export const stylistCodes: StylistCode[] = [
  { id: '1', code: 'DIST-ABC123', distributorId: '2', status: 'used', usedBy: '7', usedAt: '2024-06-01T10:30:00Z', createdAt: '2024-05-15T12:00:00Z' },
  { id: '2', code: 'DIST-DEF456', distributorId: '2', status: 'unused', createdAt: '2024-05-15T12:00:00Z' },
  { id: '3', code: 'DIST-GHI789', distributorId: '2', status: 'unused', expiresAt: '2024-12-31T23:59:59Z', createdAt: '2024-05-15T12:00:00Z' },
  { id: '4', code: 'DIST-JKL012', distributorId: '2', status: 'expired', expiresAt: '2024-05-01T23:59:59Z', createdAt: '2024-04-01T12:00:00Z' },
  { id: '5', code: 'DIST-MNO345', distributorId: '2', status: 'unused', createdAt: '2024-06-10T08:00:00Z' },
];

// TODO: Replace with API call - GET /api/coupons
export const coupons: Coupon[] = [
  {
    id: '1',
    code: 'WELCOME10',
    type: 'percent',
    value: 10,
    audience: 'all',
    usageLimit: 1000,
    usedCount: 234,
    validFrom: '2024-01-01T00:00:00Z',
    validUntil: '2024-12-31T23:59:59Z',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    code: 'STYLIST20',
    type: 'percent',
    value: 20,
    audience: 'stylist-only',
    minPurchase: 50,
    usageLimit: 500,
    usedCount: 89,
    validFrom: '2024-01-01T00:00:00Z',
    validUntil: '2024-12-31T23:59:59Z',
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '3',
    code: 'FLAT15',
    type: 'fixed',
    value: 15,
    audience: 'all',
    minPurchase: 75,
    usedCount: 156,
    validFrom: '2024-03-01T00:00:00Z',
    validUntil: '2024-06-30T23:59:59Z',
    status: 'expired',
    createdAt: '2024-03-01T00:00:00Z',
  },
];
